# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Recipes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Recipes
  # add pods for desired Firebase products
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Google-Mobile-Ads-SDK'

end
